### ISSUE TITLE
Accept scss/Material theme variables

### ISSUE THREAD

**Issue by Admiralfeb** [MurhafSousli/ngx-scrollbar#225]
#### Feature Description
When attempting to theme ngx-scrollbar, it does not accept scss variables, as far as I can see, it only accepts CSS variables.

#### Use Case
By accepting scss, it would permit better usage of consistent theming as well as Angular Material throughout an web application.
In my case, I have all my color variables defined in a _variables.scss file and I pass them to the applicable stylings files for my components.

At this point, if I try to pass a variable defined in my variables file to the scrollbar-thumb-color, it is causing the thumb to disappear. This includes a hex or a mat-palette.
I can put the hex directly on the scrollbar-thumb-color, but this is undesirable if the theme of the application ever changes.

**Comment by MurhafSousli** [comment]
@Admiralfeb I am not sure if I understand, why is it not working with CSS variable?
You can set the CSS Variable using your SCSS color variables

```scss
var(--scrollbar-thumb-color): $myThemeSecondaryColor;
```

**Comment by Admiralfeb** [comment]
ok. I was trying `--scrollbar-thumb-color: $themecolor;`
I'll try `var(--scrollbar-thumb-color): $themecolor;`

**Comment by MurhafSousli** [comment]
Here is an example with Material
```scss
ng-scrollbar {
  // Set a CSS variable from material SCSS variable
  --scrollbar-thumb-color: #{mat-color($app-primary)};
  --scrollbar-thumb-color-hover: #{mat-color(mat-palette($mat-blue, 800))};

  // Set a CSS variable from another CSS variable
  --scrollbar-size: var(--css-variable-variable);
}
```
