### ISSUE TITLE
Add feature: ability to disable transition when scrollbar thumb-size changes.

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-scrollbar#227]
Add `--scrollbar-thumb-transition` and `--scrollbar-track-transition` to set transition.

**Ex:** disable transition when scrollbar thumb-size changes.

```scss
ng-scrollbar {
  --scrollbar-thumb-transition : none
}
```
