### ISSUE TITLE
Change visibility hover duration

### ISSUE THREAD

**Issue by joxy379** [MurhafSousli/ngx-scrollbar#383]
#### Feature Description

It would be cool to hide the scrollbar based on (milli)seconds. Currently I am using visibility hover and it works as expected. But only I find the time it takes to hide too slow.

#### Use Case

I have a collapsable sidemenu with a scrollbar, only when I collapse it it takes to long for the scrollbar to dissapear. It would be nice if I could attach a time to it.

![ezgif-7-2a61babb92c2](https://user-images.githubusercontent.com/36665384/123431777-f164f400-d5c9-11eb-80e5-eb9f5010f9df.gif)

**Comment by MurhafSousli** [comment]
Currently, you can achieve this with CSS

```scss
ng-scrollbar:[visibility="hover"] {
  ::ng-deep {
    > .scrollbar-control {
      opacity: 0;
      transition-property: opacity;
      transition-duration: 400ms;
      transition-delay: 800ms;
    }

    &:hover,
    &:active,
    &:focus {
      > .scrollbar-control {
        opacity: 1;
        transition-duration: 400ms;
        transition-delay: 0ms;
      }
    }
  }
}
```

I will add a CSS variable to set the duration and delay in the future
