### ISSUE TITLE
How to change the color of the scroll bar?

### ISSUE THREAD

**Issue by leoyeung8310** [MurhafSousli/ngx-scrollbar#42]
Hi, your module is good! Easy to use and I like it very much. To further enhance the UI, may I ask you a question about how to change the color of the scroll bar??

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] question
```

### OS and Version?
macOS

### Versions
Angular CLI: 6.0.7
Node: 9.2.0
OS: darwin x64
Angular: 6.0.3

### Repro steps
I tried to override the property "background-color" of ng-scrollbar-thumb and I also tried to add a new class on the barClass first. However, in both cases, I cannot change the color of the scroll bar. Do you know why?

**Comment by MurhafSousli** [comment]
Use `thumbClass` to add custom class to the scrollbars, then you can change the color.

```html
<ng-scrollbar thumbClass="custom-scrollbars">
```
```scss
::ng-deep {  // <= add this if you are customizing the style from the component's stylesheet
  .custom-scrollbars {
    background-color: rgb(94, 175, 255) !important;

    &:hover, &:active {
      background-color: dodgerblue !important;
    }
  }
}
```
Check the [demo plunkr](https://stackblitz.com/edit/ngx-scrollbar?file=src%2Fapp%2Fhome%2Fhome.component.scss)
