### ISSUE TITLE
Using ngx-scrollbar as directive

### ISSUE THREAD

**Issue by Bykiev** [MurhafSousli/ngx-scrollbar#452]
Hi, is it possible to use ngx-scrollbar as directive? I'm migrating from [ngx-perfect-scrollbar](https://github.com/zefoy/ngx-perfect-scrollbar) and it was used this way:

```
<div class="ps" style="position: relative; max-width: 600px; max-height: 400px;" [perfectScrollbar]="config" [disabled]=isDisabled>
  <div>Scrollable content</div>
</div>
```

**Comment by MurhafSousli** [comment]
No, it is a component

**Comment by Maximaximum** [comment]
This is quite unfortunate, because a directive seems to be more appropriate for such a piece of functionality.

E.g., imagine we want to use scroll snapping on an unordered list of items:

```
<ul>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
</ul>
```

In this case, there is no clear and html-valid way to use `ngx-scrollbar`:
- If we wrap the `ul` with `<ng-scrollbar></ng-scrollbar>`, we wouldn't be able to use scroll snapping on list items, since the list items' container is `ul`, not `ng-scrollbar`;
- If we wrap the `li`s themselves with an `<ng-scrollbar></ng-scrollbar>`, we'll have an invalid html5 dom tree, since the `<ul>` element can only contain `li`s, not any other elements like `ng-scrollbar`.

**Comment by MurhafSousli** [comment]
@Maximaximum You can set the `ul` element as the scrollable element

```html

<ng-scrollbar>
  <ul scrollViewport>
    <li>1</li>
    <li>2</li>
    <li>3</li>
    <li>4</li>
    <li>5</li>
    <li>6</li>
    <li>7</li>
    <li>8</li>
    <li>9</li>
  </ul>
</ng-scrollbar>
```

```css
ul {
  display: flex;
  flex-direction: column;
  scroll-snap-type: y mandatory;
}

li {
  border-bottom: 1px solid white;
  display: flex;
  align-items: center;
  flex: 0 0 70px;
  scroll-snap-align: start;
}
```

https://stackblitz.com/edit/ngx-scrollbar-zvgwpt?file=src%2Fapp%2Fhome%2Fhome.component.html,src%2Fapp%2Fhome%2Fhome.component.scss
