### ISSUE TITLE
Upgrading from v13 to v15: different content padding

### ISSUE THREAD

**Issue by lucacervo98** [MurhafSousli/ngx-scrollbar#648]
Hi, I recently updated the library from version `13.0.3` to `15.1.3` (the latest one) and noticed a change in the **scrollbar content padding**. Previously, I was using `appearance="standard"`, but after the update, I switched to `appearance="native"`, as `"standard"` is no longer available. 

Now, regarding the vertical scrollbar: while inspecting the scrollbar in version `13`, I noticed that in addition to the `.ng-scroll-content` class (which is also present in version `15` and applies 8px of padding to the right), there was a `div` with the classes `ng-native-scrollbar-hider` and `.ng-native-scrollbar-viewport`, which added an additional 8px of padding to the right. This `div` with these classes seems to be missing in version `15`, so now I'm having 8px less of right padding for the scrollbar content.

Was this change intentional, possibly as a stylistic decision? If so, would it be possible to introduce options that allow for better configuration of the scrollbar content padding (maybe with some CSS variable overriding)?

These are the style classes that I'm using:

**v.13.0.3**
```css
ng-scrollbar {
    --scrollbar-size: 8px;
    --scrollbar-hover-size: 12px;
    --scrollbar-padding: 0px;
}
```

**v.15.1.3**
```css
ng-scrollbar {
    --scrollbar-thickness: 8;
    --scrollbar-hover-thickness: 12;
    --scrollbar-border-radius: 10px;
}
```
  
#### Environment
- Angular: `17.2.2`
- ngx-scrollbar: `15.1.3`
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

Thank you, Luca.
